### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jiolink** [ISO53/Movie-Collection-Visualizer#1]
not working in my windows 11 64 bit 

here this error please check and update

![image](https://github.com/ISO53/Movie-Collection-Visualizer/assets/39983847/7afcb505-ec41-405e-9ac5-2715e2fa7f4e)

**Comment by ISO53** [comment]
I updated the code and drafted a [new release](https://github.com/ISO53/Movie-Collection-Visualizer/releases/tag/v1.2.1). Can you check if the error persists?
