### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jiolink** [ISO53/Movie-Collection-Visualizer#2]
not working in windows 11 64bit

ombd key not repons and not adding movies option

![image](https://github.com/ISO53/Movie-Collection-Visualizer/assets/39983847/af8e956c-1c32-401e-b5ce-03f9870bc1b6)

**Comment by ISO53** [comment]
I updated the code and drafted a [new release](https://github.com/ISO53/Movie-Collection-Visualizer/releases/tag/v1.2.1). Can you check if the error persists?

**Comment by jiolink** [comment]
hi not working proper and please add play button from sourece

![image](https://github.com/ISO53/Movie-Collection-Visualizer/assets/39983847/d372583a-782e-4387-a125-de5a9e2089a8)
![image](https://github.com/ISO53/Movie-Collection-Visualizer/assets/39983847/4a2a49c9-3a26-448e-90f7-e5acedac9f06)

**Comment by jiolink** [comment]
and my file i dont know way deleted after adding movies

![image](https://github.com/ISO53/Movie-Collection-Visualizer/assets/39983847/03c8d9f8-d67c-417f-bbbe-041d7c396a11)

**Comment by ISO53** [comment]
I will work on this bug. In the meantime please submit your **new feature request** by opening another issue with `enhancement` tag.

**Comment by ISO53** [comment]
I drafted a [new release](https://github.com/ISO53/Movie-Collection-Visualizer/releases/tag/v1.2.2) that hopefully solves all of your problems. If it does can you please let me know so i can close this issue. Oh also you can now directly download the app from my [new website](https://iso53.github.io/Movie-Collection-Visualizer#download).
